# Generated by Django 6.1.1 on 2026-10-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.chore')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chores', models.ManyToManyField(through='chores.Assignment', to='chores.chore')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='family_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.familymember'),
        ),
    ]
